### ISSUE TITLE
Minor types in paper

### ISSUE THREAD

**Issue by geraintpalmer** [martinfleis/momepy#105]
Hi @martinfleis, I believe there are some very minor typos in the paper:

Second paragraph on page 2:

 > Additionally, the utils module helps, among other others

Final paragraph on page 2:

 > Under the hood uses PySAL,

Final paragraph on page 2:

 > As momepy is part of Python geospatial stack of libraries

None of these are major at all.

**Comment by martinfleis** [comment]
Thank you, should be fixed now.
