### ISSUE TITLE
Confusing print statement

### ISSUE THREAD

**Issue by DavidMStraub** [martinfleis/momepy#141]
Hi,

thanks for this useful library. I use in particular the `gdf_to_nx` and `nx_to_gdf` functions in my code. However, when I import:

```python
from momepy import gdf_to_nx, nx_to_gdf
```
The string `rtd` is printed. This caused quite some confusion and it took me a while to trace this down to `momepy`. It comes from this in `momepy.elements`:

```python
try:
    from osgeo import ogr
except ModuleNotFoundError:
    print("rtd")
```

Indeed I don't have the GDAL Python bindings installed in my virtualenv, but the  `gdf_to_nx` and `nx_to_gdf` functions work flawlessly.

So my suggestion would be:
- import `ogr` only in the modules that require it (or only in the functions that require it)
- raise an error or emit a warning in case a required module is not found rather than printing something.

Thanks again.

PS: Using momepy 0.1.1 with Python 3.7.5 on Ubuntu.

**Comment by martinfleis** [comment]
Hi @DavidMStraub,

you are absolutely right. This is a dirty lazy patch to make readthedocs work as there is an issue with mocking `osgeo`. 

`ogr` is needed only for `Tessellation`, so it makes sense to import it when needed and raise warning in that case only. Ideally it should raise error, but that would break readthedocs again. I have to find a way around it.

It happens here: https://github.com/martinfleis/momepy/blob/429f7b95ad390c6ce5d45743f7b7cf77235e42d6/momepy/elements.py#L288

I'll fix that in following days. Or feel free to make a PR yourself if you are willing to.

Thanks!
