### ISSUE TITLE
No support for LINESTRING Z `nx_to_gdf` fails

### ISSUE THREAD

**Issue by LeonardAukea** [martinfleis/momepy#142]
Nice lib! 

I noticed that you wont be able to convert a network back to a gdf if it has elevation data `gdf.has_z == True` . This is due to how `_points_to_gdf` is implemented ->  

```
def _points_to_gdf(net, spatial_weights):
    """
    Generate point gdf from nodes.
    Helper for nx_to_gdf.
    """
    node_xy, node_data = zip(*net.nodes(data=True))
    gdf_nodes = gpd.GeoDataFrame(
        list(node_data), geometry=[Point(i, j) for i, j in node_xy]
    )
    gdf_nodes.crs = net.graph["crs"]
    return gdf_nodes
```

Either some changes has to be made to the code or there should be some mention of this in docs. 
potentially one could add a check  and remove it on the fly.  I had to do this of 3D->2D conversion (`LINESTRING Z` -> `LINESTRING`): 

```
gdf.geometry.apply(lambda geom: shapely.wkb.loads(shapely.wkb.dumps(geom, output_dimension=2)))
```

**Comment by martinfleis** [comment]
Hi, thanks for the notice. I didn’t realise this option, so it is not implemented. But it should be, it is not an intention. Ideally you should get Point Z in the example above. Would you like to make a PR fixing it?

**Comment by martinfleis** [comment]
@LeonardAukea I just merged a PR adding a support of Z coordinates (#148). If you could check if it resolves your issue, that'd be great!
