### ISSUE TITLE
global betweenness and local betweenness 

### ISSUE THREAD

**Issue by ngocfulbright** [martinfleis/momepy#160]
Dear Martin,

I have an issues with local betweenness. Whenever I run global betweenness with local betweenness, I have the exact the same values of the mean betweenness, despite that I changed locations and radii. I don't know why. In this example, I used a location in Khalifa City, Abu Dhabi, UAE.
Thank you very much,
Nguyen

```py
import geopandas as gpd
import momepy
import pandas as pd

import osmnx as ox
import matplotlib.pyplot as plt


location_point = (24.417827, 54.554158)


G = ox.graph_from_point(location_point, distance= 804, distance_type='bbox', network_type='drive_service')
G = ox.project_graph(G)
fig, ax = ox.plot_graph(G, filename= 'Khalifa2, Abu Dhabi', dpi = 1200, file_format='png', save=True, node_size=0, node_color='#66cc66')


edges = ox.save_load.graph_to_gdfs(G, nodes=False, edges=True,
                                   node_geometry=False, fill_edge_geometry=True)

f, ax = plt.subplots(figsize=(7, 7))
edges.plot(ax=ax, linewidth=0.2)
ax.set_axis_off()
plt.show()

primal = momepy.gdf_to_nx(edges, approach='primal')
primal = momepy.betweenness_centrality(primal, name='betweenness_metric_e', mode='edges', weight='mm_len')

primal_gdf = momepy.nx_to_gdf(primal, points=False)
f, ax = plt.subplots(figsize=(7, 7))
primal_gdf.plot(ax=ax, column='betweenness_metric_e', cmap='Spectral_r', scheme='quantiles', alpha=0.8)
ax.set_axis_off()
ax.set_title('global betweennes edge based')
plt.show()


global_betweenness = primal_gdf['betweenness_metric_e'].mean()
print (global_betweenness)
primal_gdf['betweenness_metric_e'].max()

primal = momepy.local_betweenness_centrality(primal, radius=400, distance='weight', weight ='mm_len')


primal_gdf = momepy.nx_to_gdf(primal, points=False)
f, ax = plt.subplots(figsize=(8, 8))
primal_gdf.plot(ax=ax, column='betweenness_metric_e', cmap='Spectral_r', scheme='quantiles', alpha=0.8)
ax.set_axis_off()
ax.set_title('local betweennes edge based R400')
plt.show()

local_betweennessR400 = primal_gdf['betweenness_metric_e'].mean()
print (local_betweennessR400)

primal_gdf.max
primal_gdf.head(600)
```

In this example, I have the same value of 0.05403382736448154 for the mean of global and local betweenness. They are supposedly different. Thank you very much.

**Comment by martinfleis** [comment]
You are comparing the same column, same values. Not global with local betweenness. `momepy.betweenness_centrality` with `mode='edges'` calculates value for each edge. `momepy.local_betweenness_centrality` does not allow that as it has to generate subgraph around nodes, so all values are initially on nodes, not edges. 

Also, you have not specified name of local betweenness attributes, so it uses the default `'betweenness'`. 

You have two options here:
1) work with nodes with local betweenness. then you need to convert Graph to nodes (points), and plot according to default name (unless you want to specify it):
```py
primal_gdf = momepy.nx_to_gdf(primal, edges=False, points=True)
f, ax = plt.subplots(figsize=(8, 8))
primal_gdf.plot(ax=ax, column='betweenness', cmap='Spectral_r', scheme='quantiles', alpha=0.8)
```

2) Get mean value of end nodes betweenness for edges and change only the name of column to correct one.
```py
momepy.mean_nodes(primal, 'betweenness')

primal_gdf = momepy.nx_to_gdf(primal, points=False)
f, ax = plt.subplots(figsize=(8, 8))
primal_gdf.plot(ax=ax, column='betweenness', cmap='Spectral_r', scheme='quantiles', alpha=0.8)

local_betweennessR400 = primal_gdf['betweenness'].mean()
```

**Comment by ngocfulbright** [comment]
Thank you very much. I selected the second option. Nevertheless, I got the raw value instead of a normalized value of the mean of betweenness. 
The value for this specific location is 
797.2552631578948

Is there any way to get the normalized values?


The codes for the second option: 
primal = momepy.local_betweenness_centrality(primal, radius=400, weight ='mm_len')

momepy.mean_nodes(primal, 'betweenness')

primal_gdf = momepy.nx_to_gdf(primal, points=False)
f, ax = plt.subplots(figsize=(8, 8))

primal_gdf.plot(ax=ax, column='betweenness', cmap='Spectral_r', scheme='quantiles', alpha=0.8)
ax.set_axis_off()
local_betweennessR400 = primal_gdf['betweenness'].mean()

print (local_betweennessR400)

**Comment by martinfleis** [comment]
> Is there any way to get the normalized values?

Yes, just set `normalized=True` in `momepy.local_betweenness_centrality`.

```py
primal = momepy.local_betweenness_centrality(primal, radius=400, weight ='mm_len', normalized=True)
```

See docs for all the options:
http://docs.momepy.org/en/stable/generated/momepy.local_betweenness_centrality.html#momepy.local_betweenness_centrality

**Comment by ngocfulbright** [comment]
Thank you very much! It works
