### ISSUE TITLE
BUG: UnboundLocalError: local variable 'cpu_count' referenced before assignment

### ISSUE THREAD

**Issue by mmerrittsmith** [martinfleis/momepy#265]
Hello, 

When trying to run Momepy's user guide [here](http://docs.momepy.org/en/stable/user_guide/elements/enclosed.html#id2) on enclosed tessellations, I'm getting the following error:

```
Traceback (most recent call last):
  File "path/morph_tess_prclz_data.py", line 35, in <module>
    enclosed_tess = momepy.Tessellation(buildings, unique_id='uID', enclosures=enclosures).tessellation
  File "conda_env_path/site-packages/momepy/elements.py", line 225, in __init__
    self.tessellation = self._enclosed_tessellation(
  File "conda_env_path/site-packages/momepy/elements.py", line 462, in _enclosed_tessellation
    n_chunks = cpu_count() - 1 if cpu_count() > 1 else 1
UnboundLocalError: local variable 'cpu_count' referenced before assignment
```

I'm not sure how to go about creating a minimal reproducible example here, since I'm not sure how this works on others' computers. The error results on my computer from just running the examples as written in the user guide. 

Thank you!

**Comment by martinfleis** [comment]
Whoops. It happens if you don't have `dask` installed in your environment. The condition checking for it is a bit clumsy.

If you specify `use_dask=False` manually in `momepy.Tessellation` it should work. I'll push a fix for this.

Thanks a lot for the notice! Since I normally have `dask` installed, I did not notice.

**Comment by martinfleis** [comment]
@mmerrittsmith It is now fixed on master. I will make a quick bug release with this as it can be annoying. You can expect v0.4.3 on PyPI in few minutes and on a conda-forge couple of hours later. Thanks again for the report.

**Comment by mmerrittsmith** [comment]
Thank you for the quick fix!
