### ISSUE TITLE
BUG: Weight matrix generated from libpysal inconsistent with adjacency computation.

### ISSUE THREAD

**Issue by jonwangio** [martinfleis/momepy#267]
After creating some weights with the tessellation through:

```
queen_1 = Queen.from_dataframe(city_tess, ids="uID")
```

A sparse version of the weights further through libpysal:

```
w = queen_1.sparse
wk = sum(map(lambda x: w ** x, range(2, 4)))
queen3 = libpysal.weights.WSP(wk).to_W()

```
raised error message:

```
Traceback (most recent call last):

  File "<ipython-input-5-1d739aeb307a>", line 4, in <module>
    city['ltcBuA'] = mm.BuildingAdjacency(city, queen3, 'uID', city_queen).series

  File "C:\Users\Jon\Anaconda3\lib\site-packages\momepy\distribution.py", line 791, in __init__
    if neighbours:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by martinfleis** [comment]
This is caused by the fact that `W.neighbors[n]` is returned as an array, not list (which is expected here), which was (I hope) fixed in https://github.com/pysal/libpysal/pull/186. Since I am not able to reproduce the issue, you most likely have outdated libpysal.

**Comment by jonwangio** [comment]
> This is caused by the fact that `W.neighbors[n]` is returned as an array, not list (which is expected here), which was (I hope) fixed in [pysal/libpysal#186](https://github.com/pysal/libpysal/pull/186). Since I am not able to reproduce the issue, you most likely have outdated libpysal.

Thanks. I even think this is due to `python 3.7.3` as it never happened before until I jumped from 3.6 to 3.7. In 'python 3.7.3', my `geopandas` always starts from 0.6.3 by using:

`conda install --channel conda-forge geopandas`

given this 0.6.3 version of `geopandas`, the 'libpysal' would stick to 4.1.1, which also is not the most up-to-date.

**Comment by martinfleis** [comment]
0.6.3? that is a fairly old release (current is 0.9.0). conda install normally returns 0.9 now (and I highly recommend having geopandas 0.9 and pygeos 0.9 now since it can bring super performance enhancements).

**Comment by jonwangio** [comment]
> 0.6.3? that is a fairly old release (current is 0.9.0). conda install normally returns 0.9 now (and I highly recommend having geopandas 0.9 and pygeos 0.9 now since it can bring super performance enhancements).

Definitely no problem with the `geopandas 0.9.0`. The issue is a bit clear now if the `libpysal` is > 4.1.
