### ISSUE TITLE
Enclosure has problems with rivers

### ISSUE THREAD

**Issue by ale-v** [martinfleis/momepy#270]
Although I specified streets and land as spatial constraints for generating the enclosures, the momepy.enclosures wrongly creates enclosures in rivers. See the yellow areas in the pic. 
![wards](https://user-images.githubusercontent.com/26009465/110358455-b8b20680-803c-11eb-883e-c6299613d882.jpeg)

**Comment by martinfleis** [comment]
I think that we'll have to add some spatial filter before we return polygons. The operation itself is just `polygonize`, that's why these areas are returned. I just don't want to do it every time because it can be expensive. Will have to figure out some smart solution.
