### ISSUE TITLE
Get the list of nodes connected to each node 

### ISSUE THREAD

**Issue by orbitlink** [martinfleis/momepy#272]
Hello,

Is there a simple way to get the list of nodes (nodeID) connected to each nodes of a graph? 
The methods from networkx like neighbors(G, n) seems not to be adapted here because it applies to the node as coordinates. Apparently you can't choose the node identifier as an attribute. Thanks a lot. 
```
...
frame = geopandas.read_file('linestring.geojson')
graph = momepy.gdf_to_nx(frame, approach="primal")

#allnode = dict(nx.neighbors(graph, ?))
#nx.set_node_attributes(graph, allnode, 'neighbors')

nodes, edges, sw = momepy.nx_to_gdf(graph, points=True, lines=True,
                                    spatial_weights=True)
```

**Comment by martinfleis** [comment]
Hi,

that is not possible from the Graph object because `nodeID` you get from `momepy.nx_to_gdf` is generated at that point. It is not present in the Graph itself. However, all that information is encoded in spatial weights you also get and you that stores a dictionary of neighbours. See the example:

```py
frame = geopandas.read_file(momepy.datasets.get_path('bubenec'), layer="streets")
graph = momepy.gdf_to_nx(frame, approach="primal")

nodes, edges, sw = momepy.nx_to_gdf(graph, points=True, lines=True,
                                    spatial_weights=True)

sw.neighbors
```
```
{0: [1, 6, 8],
 1: [0, 3, 4, 9, 28],
 2: [3, 9, 25],
 3: [1, 2, 15, 22],
 4: [1, 6, 22, 23],
 5: [6, 10],
 6: [0, 4, 5, 23],
 7: [8],
 8: [0, 7],
 9: [1, 2, 11, 27],
 10: [5],
 11: [9, 12, 13, 14],
 12: [11],
 13: [11],
 14: [11, 24, 25],
 15: [3, 16, 19, 20],
 16: [15, 17, 25],
 17: [16],
 18: [19],
 19: [15, 18],
 20: [15, 21, 22, 26],
 21: [20],
 22: [3, 4, 20],
 23: [4, 6],
 24: [14],
 25: [2, 14, 16],
 26: [20],
 27: [9],
 28: [1]}
```

So `sw.neighbors[20]` gives you nodeIDs of nodes neighbouring node with ID 20 etc. 

Does that resolve you issue?

**Comment by orbitlink** [comment]
Great! Yes thank you very much @martinfleis , issue solved. To go further, are there any other methods applicable to `sw` ? I looked at the reference API but I don't think I saw any information about it.

**Comment by martinfleis** [comment]
Yes, what you get as `sw` here is `libpysal.weights.W` object which has a lot of other attributes and linked functions you can play with. Check the documentation here: https://pysal.org/libpysal/generated/libpysal.weights.W.html#libpysal-weights-w

**Comment by orbitlink** [comment]
Yes, I had just found it. Thanks again for everything.

**Comment by martinfleis** [comment]
Happy to help!
