### ISSUE TITLE
Mismatch between the identifiers of the momepy and libpysal nodes. 

### ISSUE THREAD

**Issue by orbitlink** [martinfleis/momepy#273]
This question is a follow-up to question #272 

The nodeIDs we get from `momepy.nx_to_gdf` seem to be different by one index from those encoded in the spatial weights of type `libpysal.weights.W`. So for example, when we look for the dictionary of neighbors with the `.neighbors` attribute, to use @martinfleis 's example, we have :
```python
{0: [1, 6, 8],
 1: [0, 3, 4, 9, 28],
 2: [3, 9, 25],
 3: [1, 2, 15, 22],
 4: [1, 6, 22, 23],
 5: [6, 10],
 6: [0, 4, 5, 23]}
...
```
But the nodeID number `0` does not exist in the frame generated by momepy. So for example we get :
```python
frame = geopandas.read_file('edges.geojson')
graph = momepy.gdf_to_nx(frame, approach="primal")
nodes, edges, sw = momepy.nx_to_gdf(graph, points=True, lines=True,
                                    spatial_weights=True)

nodes['neighbors'] = pandas.Series(sw.neighbors)
print(nodes)
```
```python
      nodeID                   geometry     neighbors
0          1   POINT (42.70275 9.94481)        [1, 2]
1          2   POINT (42.70030 9.94783)     [0, 2, 3]
2          3   POINT (42.69700 9.97133)     [0, 1, 3]
3          4  POINT (42.60179 10.34216)        [1, 2]
4          5  POINT (44.18208 10.27975)        [5, 6]
...      ...                        ...           ...
2674    2675  POINT (38.49058 29.05764)  [2301, 2302]
2675    2676  POINT (38.04508 31.69193)  [2672, 2673]
2676    2677  POINT (38.28310 31.55440)  [2677, 2678]
2677    2678  POINT (38.31708 31.58690)  [2676, 2678]
2678    2679  POINT (38.27884 31.61838)  [2676, 2677]
```
**The id of a node can have its own id as neighbor**. For example here, with the nodeID number 1.
Does momepy support this difference in any way? Thanks.

**Comment by martinfleis** [comment]
Ah, true. What comes from `sw` is actually integer location. I guess that `nodeID` should also start at 0 here: https://github.com/martinfleis/momepy/blob/ec7f172806d8390f38ee61104ce1b2a2bab7fd82/momepy/utils.py#L420

You can get the matching ID by substracting 1 from nodeID as 

```py
nodes["fixed_ID"] = nodes["nodeID"] -1
```

or use `iloc` indexing.

**Comment by martinfleis** [comment]
This actually caused a bug in `NodeDensity`, which also assumed that `nodeID` and the ID stored in `sw` match 🤦. I will make a bugfix release today.

Thanks a lot for catching this!

**Comment by orbitlink** [comment]
Oh yes ! Indeed it can cause bugs in some places. For example in the generated dataframe `edges`. 
It is also necessary to apply subtraction to `node_start` and `node_end` like : 
```python
edges["node_start"] = edges["node_start"] - 1
edges["node_end"] = edges["node_end"] - 1
```

This change can perhaps cause other bugs elsewhere.

**Comment by martinfleis** [comment]
This fix is now released. It is already available via `pip` and in a few hour will also be on conda-forge.
