### ISSUE TITLE
momepy.enclosures doesn't appear to observe limit parameter

### ISSUE THREAD

**Issue by matthew-law** [martinfleis/momepy#287]
When building enclosures with `momepy.enclosures`, the `limit` parameter doesn't seem to be observed. Looking through the code, my best guess is that [this line](https://github.com/martinfleis/momepy/blob/v0.4.4/momepy/elements.py#L988) of the source adds the `primary_barriers` and the `limit` together when defining the barriers to create the enclosures within, thereby expanding the supplied `limit` to also include the area bounded by the `primary_barriers`, but I could be wrong.

[Here](https://gist.github.com/matthew-law/7b5c29ae31a72f02c43f195d37b26705) is a notebook showing an example – the final plot shows enclosures outside of the supplied `limit`.

Alternatively, I've misunderstood the docs and `limit` is not meant to be the definitive geographical boundary within which the enclosures are generated.

**Comment by martinfleis** [comment]
It is the same issue as discussed in #270. `limit` is added to the mix with boundaries which is fed to `polygonize`.  We don't check for this afterward. It may be actually worth doing that and dropping geometries outside.

**Comment by matthew-law** [comment]
My workaround so far has been to subset the enclosures generated to only include those within a 1m buffer of the limit (see below), but I don't think this would be ideal to incorporate into `momepy.enclosures` itself, since the size of the buffer will change dependent on the CRS, and idiosyncratic data could always still yield a small enclosure that fits within that buffer and so gets missed when subsetting. I'm not too sure what the best alternative way to check for geometries outside of the limit would be, though.

```python
# subset enclosures to only include those within a 1m buffer of the limit
enclosures = enclosures[enclosures.within(limit.buffer(1)[0])]
```

**Comment by martinfleis** [comment]
We can do something along these lines, ideally backed by spatial index. Alternatively, we can clip the input barriers by limit. That may actually be easier and more efficient at the same time.
